id: P0F309DAE
initial_creation_type: ebook
source_metadata:
  title: test
  subtitle: test
  authors:
  - test
  collection: test
  publisher: test
  id: sku
  cover: tmp71mh6_c1.jpg
  credit: tmp3hz8q5_k.jpg
created_at: null
last_modified_at: null
